fpga_compile code sample
KevinUTAT/oneAPI-samples pull request #1
Opened 2022-11-17 13:32 UTC by KevinUTAT

# Existing Sample Changes
## Description

The fpga_compile tutorial is updated to have 3 different parts: C++, functor-USM and Lambda-Buffer. It's also updated to have co-simulation support. The source code is ported from [oneapi_demo](https://github.com/intel-sandbox/whitepau.oneapi-demo-duncan).

## External Dependencies

No change.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Command Line

2022-11-18 16:38 UTC, whitepau requested changes
Good start. Please update to 2023.0.

This will be a great improvement to this tutorial.

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| FPGA Simulator  | minutes         | Compiles the FPGA device code to RTL and generates a simulation testbench. Use the Questa*-Intel® FPGA Edition simulator to verify your design.
```suggestion
| FPGA Simulator       | minutes         | Compiles the FPGA device code to RTL and generates a simulation testbench. Use Siemens* Questa*-Intel® FPGA Starter Edition (or Siemens* Questa*-Intel® FPGA Edition) to verify your design.
```
Add spaces to align the table properly

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  While SYCL* code can be compiled for CPU, GPU, or FPGA, compiling to FPGA is somewhat different. This tutorial explains these differences and shows how to compile a "Hello World" style vector additio
I can't comment on line 8, but please change it to this:

```
| Software                          | Intel® oneAPI DPC++/C++ Compiler <br> Intel® Quartus® Prime Pro Edition <br> Intel® Platform Designer Prime Pro Edition <br> Siemens*  Questa*-Intel® FPGA Starter Edition (or Siemens* Questa*-Intel® FPGA Edition)
```

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  This is a full compile through to the FPGA hardware image. You can target the Intel® PAC with Intel Arria® 10 GX FPGA, the Intel® FPGA PAC D5005 (with Intel Stratix® 10 SX), or a custom device.
```suggestion
This is a full compile through to the FPGA hardware image. You can target the Intel® PAC with Intel Arria® 10 GX FPGA, the Intel® FPGA PAC D5005 (with Intel Stratix® 10 SX), or a custom device with a compatible Board Support Package (BSP).
```

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +In the FPGA IP Authoring flow, you target your SYCL* code to generate IP components that you can integrate into custom system. You target your compilation to a supported Intel® FPGA device family or
```suggestion
In the FPGA IP Authoring flow, you generate a reusable IP component from your SYCL* code instead of a full FPGA image. You can import this IP into an Intel® Quartus® Prime project. You can generate a standalone IP by target your compilation to a supported Intel® FPGA device family or part number instead of an Intel® PAC or other custom device.
```

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +### Compile for IP Components
```suggestion
### Reusable IP Component
```

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +
Line 71-78 is redundant. to line 49-55

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/part1-C++/src/CMakeLists.txt
> +###############################################################################
Please use this CMakeLists.txt instead:

https://github.com/whitepau/oneAPI-samples/blob/add-empty-design/DirectProgramming/DPC%2B%2BFPGA/Tutorials/GettingStarted/experimental/fpga_template/src/CMakeLists.txt

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/part1-C++/src/Makefile
> +SRC:= vector_add.cpp
remove makefiles please

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +icpx -fxycl -fintelfpga fpga_design.cpp -Xssimulation -Xstarget=Agilex -Xsghdl -DFPGA_SIMULATOR
```suggestion
icpx -fsycl -fintelfpga fpga_design.cpp -Xssimulation -Xstarget=Agilex -DFPGA_SIMULATOR
```
i notice lots of these typos later on too.

`-Xsghdl` does nothing.

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| `-Xstarget=<FPGA device family>`<br>`-Xstarget=<FPGA part number>`<br>`-Xstarget=<bsp:variant>` | [Optional] Instructs the compiler to target an part number, or an FPGA board as follows:<br> `-Xsta
```suggestion
| `-Xstarget=<FPGA device family>`<br>`-Xstarget=<FPGA part number>`<br>`-Xstarget=<bsp:variant>` | [Optional] Instructs the compiler to target a part number, or an FPGA board as follows:<br> `-Xstarget=<FPGA device family>` specifies the target FPGA device family. Valid values are `CycloneV`, `Agilex`, `Arria10`, and `Stratix10`.<br> `-Xstarget=<FPGA part number>` specifies the target FPGA part number (sometimes called an OPN). You can specify any valid Cyclone® V, Intel® Agilex™, Intel® Arria® 10, or Intel® Stratix® 10 part number.<br> `-Xstarget=<bsp:variant>` specifies the FPGA board variant and BSP.<br> If you omit the `-Xstarget` flag, the compiler chooses the default FPGA board variant `pac_a10 from the intel_a10gx_pac` BSP (equivalent to `-Xstarget=intel_a10gx_pac:pac_a10`).
```
This table entry is very difficult to read; does this look better broken out into separate rows?

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  Notice that whether you target the FPGA emulator or FPGA hardware must be specified twice: through compiler options for the ahead-of-time compilation and through the runtime device selector.
This sentence is so hard to read; i do not understand it.

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  ### Running Samples in Intel&reg; DevCloud
```suggestion
### Running Samples in Intel® DevCloud
```
please use the unicode character instead.

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +For best results, use Linux. This design uses CMake to build the project. For different parts of this tutorial, navigate to the appropriate sub-folder, generate build artifacts for GNU/make targeting
what about linux gives better results? The original demo-duncan that this code is based off had this line in the readme because it used Makefiles (which don't work by default on Windows), but this design now uses CMake so it will work equally well on Windows and Linux (unless there is a different tradeoff).

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +For best results, use Linux. This design uses CMake to build the project. For different parts of this tutorial, navigate to the appropriate sub-folder, generate build artifacts for GNU/make targeting
```suggestion
For best results, use Linux. This design uses CMake to build the project. For different parts of this tutorial, navigate to the appropriate sub-folder, generate build artifacts for GNU/make targeting the default FPGA device specified in `src/CMakeLists.txt` like this:
```

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +To target an explicit FPGA device like this:
```suggestion
Override the `FPGA_DEVICE` variable to target a different FPGA device like this:
```

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +This project can build 8 targets for Linux.
```suggestion
This project can build 4 targets for Linux.
```

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| Target                     | Expected Time  | Output                                                        | Description
this table seems redundant to an earlier table. can we condense this very very very long readme by removing one of them?

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +To target an explicit FPGA device like this:
same as above

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +This project can build 8 targets for Windows.
same as above

2022-11-18 16:38 UTC, whitepau commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +PASSED
that seems anticlamctic; I would have expected a bit more verbosity :)

2022-11-18 16:40 UTC, yuguen-intel commented
Paul beat me to the review - please ping me when you have addresses his remarks - thanks!

2022-11-18 20:34 UTC, KevinUTAT commented
Updated to 2023.0, resolving all of Paul's suggestions

2022-11-30 14:02 UTC, KevinUTAT commented
merge Paul's changes to readme

2022-12-01 11:54 UTC, yuguen-intel requested changes

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| FPGA Simulator       | 10-15 minutes   | Compiles the FPGA device code to RTL and generates a simulation testbench. Use Siemens* Questa*-Intel® FPGA Starter Edition (or Siemens* Questa*-Intel® FPGA
At this moment "RTL" has not been defined. 
Also the same remarks as in the requirements applies, we don't know yet exactly what should be put there for the simulator.

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| FPGA Hardware        | hours           | Generates an FPGA bitstream in full-system acceleration kernel. Generates accurate resource/performance estimates for reusable IP component.
Are these really estimates for reusable IPs? These will be actual quartus numbers right?

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +
I think it would be beneficial to explain that the simulation is completely transparent to the user, that they do not have to open modelsim and create a testbench and so on.
They'll run their executable as usual, it's just that the FPGA part will run in a simulator under the hood.
However, they can open modelsim to debug an issue, etc.

I realize it's hard to motivate opening modelsim as it would be telling them to debug an issue with our compiler...

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The generated Verilog RTL is mapped onto the FPGA's sea of primitive hardware resources by the Intel® Quartus® Prime software. The estimated performance and resource utilization is therefore much mor
Please tell that the reusable IP is not an executable in another paragraph to really separate the two.
Or make a bullet list with the two options

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +#elif FPGA_HARDWARE
This is a change compared to all the other samples.
Do we want to make it different only for this sample?
Usually the EMULATOR is the one defined, and FPGA_HARDWARE is not defined

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> -Notice that the FPGA emulator and the FPGA are different target devices. It is recommended to use a preprocessor define to choose between the emulator and FPGA selectors. This makes it easy to switch
Why removing this paragraph?

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +# FPGA early image (with optimization report): FPGA device family
Maybe show one command and have a note showing the different options for --Xstarget?

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +icpx -fsycl -fintelfpga -DFPGA_SIMULATOR fpga_design.cpp -Xssimulation -Xstarget=Agilex -o fpga_design_sim.a
Some need -ghdl but I'm not sure which please check

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| `-fintelfpga`                    | Perform ahead-of-time compilation for FPGA.
This is not really accurate, as we use this as well for emulation
It is used for having our FPGA hooks

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| `-fsycl-link=early`              | Instructs the compiler to stop after creating the FPGA early image (and associated optimization report). No executable (co-simulation or FPGA bitstream) is create
Please explain that this needs to be used alongside the -Xshardware flag

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +A vector addition program in vanilla C++. This program can only be be compiled with the FPGA emulator compilation type.
Humm, if this is vanilla C++, why the FPGA emulator? 
Isn't it just a CPU compile?

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +There are 3 parts to this tutorial located in the 3 sub-folders.
You should motivate these 3 parts, explaining that this is a help to show the users how to start from a C++ code and make it evolve to a SYCL FPGA code

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +$> mkdir build
Please remove all the $> and > as they are not consistent with the rest of the samples.

Please add a line saying `cd partX-XXX` before the `mkdir build`

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +$> mkdir build
You can factor out the mkdir build and cd build for all these commands.

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> -> **Note**: If you encounter any issues with long paths when compiling under Windows*, you may have to create your ‘build’ directory in a shorter path, for example c:\samples\build.  You can then run
Why removing this paragraph?

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The `fpga_emu` and `fpga_sim` targets produce binaries that you can run. The executables will be called `TARGET_NAME.fpga_emu`, `TARGET_NAME.fpga_sim`, and `TARGET_NAME.fpga`, where `TARGET_NAME` is
It's not the value that the user specified, it's the value we specified.
So you can actually list them

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +If you encounter any issues with long paths when compiling under Windows*, you may have to create your ‘build’ directory in a shorter path, for example `c:\samples\build`.  You can then run cmake fro
Oh it is here, cool

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +Windows:
I think that this is a bit too much and can be removed?

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/part1-C++/src/CMakeLists.txt
> +### Customize these build variables
99% of this cmake can be removed
We just need icpx vector_add.cpp

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +#elif FPGA_HARDWARE
Same remark as in the README, this is not the same as all the other samples, please make it consistent

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +using namespace sycl;
Explicitly use `sycl::` in the code below and remove this line

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/part3-dpcpp_lambda_buffers/src/vector_add.cpp
> +using namespace sycl;
Explicitly use `sycl::` in the code below and remove this line

2022-12-01 11:54 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/part3-dpcpp_lambda_buffers/src/vector_add.cpp
> +#elif FPGA_HARDWARE
Same remark about consistency across code samples

2022-12-01 21:44 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| FPGA Hardware        | hours           | Generates an FPGA bitstream in full-system acceleration kernel. Generates accurate resource/performance estimates for reusable IP component.
The reference I can find is in _Synthesizing Your Component IP with Intel Quartus Prime Software_ where it states: "Typically, Intel Quartus Prime compilation times can take minutes to hours, depending on the size and complexity of your IP components."

2022-12-02 21:28 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| Software                          | Intel® oneAPI DPC++/C++ Compiler <br> Intel® Quartus® Prime Pro Edition <br> Intel® Platform Designer Prime Pro Edition <br> Siemens*  Questa*-Intel® FPGA Starte
I will note down to update this before the public PR

2022-12-02 21:41 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> -Notice that the FPGA emulator and the FPGA are different target devices. It is recommended to use a preprocessor define to choose between the emulator and FPGA selectors. This makes it easy to switch
Added back

2022-12-02 21:42 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +#elif FPGA_HARDWARE
Changed to the same as other samples

2022-12-02 21:44 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +icpx -fsycl -fintelfpga -DFPGA_SIMULATOR fpga_design.cpp -Xssimulation -Xstarget=Agilex -o fpga_design_sim.a
right, add -Xsghdl

2022-12-02 21:57 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The `fpga_emu` and `fpga_sim` targets produce binaries that you can run. The executables will be called `TARGET_NAME.fpga_emu`, `TARGET_NAME.fpga_sim`, and `TARGET_NAME.fpga`, where `TARGET_NAME` is
right, change all TARGET_NAME to vector_add

2022-12-06 10:13 UTC, yuguen-intel requested changes

2022-12-06 10:13 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The FPGA IP component authoring flow will not generate any FPGA accelerated executable, only RTL (Register Transfer Level) IP component files. The host application will only be treated as a 'testbenc
Can you add something along the lines of:
When compiling for FPGA using the full board design, the compiler will interface your design with the BSP and quartus will compile the entire design. Your host application will then seamlessly make the system calls to launch the kernels on the FPGA. 
When compiling for FPGA using the IP flow, Quartus will only compile for the IP is isolation, not connected to anything else on the FPGA, making the generated bitstream unusable. This flow will only be used to get accurate resource usage data of the generated IP that will need to be integrated into a larger RTL project.

2022-12-06 10:13 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| FPGA Hardware        | hours           | Generates an FPGA bitstream in full-system acceleration kernel. Generates accurate resource/performance estimates for reusable IP component.
```suggestion
| FPGA Hardware        | hours           | Generates an FPGA bitstream in full-system acceleration kernel. Generates accurate resource usage and performance estimates for reusable IP component.
```

2022-12-06 10:13 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +
I don't think that you addressed this comment

2022-12-06 22:03 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +
Re-write this section to be aligned with to the programing guide

2022-12-06 23:08 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The FPGA IP component authoring flow will not generate any FPGA accelerated executable, only RTL (Register Transfer Level) IP component files. The host application will only be treated as a 'testbenc
I think this is a better fit to the `#### FPGA hardware` section on line 71

2022-12-08 14:40 UTC, erickoeck commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +> - ModelSim® SE
ModelSim SE isn't listed as a supported simulation tool for Quartus any more.

Change this to "Siemens EDA Questa Advanced Simulator" for the first use. If you need to mention it later, you can just say "Questa Advanced Simulator", but typically you can avoid that and address all 3 supported simulators by say "...a Questa simulator..." or "...Questa simulation software..."

2022-12-08 14:40 UTC, erickoeck commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The optimization report, sometimes called the "static report," contains significant information about how the compiler has transformed your device code into an FPGA design. The report includes visual
Use double-quotes instead of single-quotes here.

2022-12-08 14:40 UTC, erickoeck commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +```
After the code block, can you add the list of parts or would that be redundant?
For example:

Where _&lt;partX-XX&gt;_ is one of the following:

- part1-C++
- part2-dcpcpp_functor_usm
- part3-dcpcpp_lambda_buffers

2022-12-08 15:35 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +> - ModelSim® SE
Interesting, I've asked around but no one really complained about ModelSim SE.
I'll make a note about it and update all the other code samples, thanks Eric!

2022-12-08 15:37 UTC, erickoeck commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +> - ModelSim® SE
It's nothing urgent to update, but we should move towards the new name as we make updates.

2023-01-18 15:45 UTC, KevinUTAT commented
# Regtests result
## Linux
https://spetc.intel.com/testanalysis?trview=0&testRunIds=7451962&tapgsize=20 \
Tested with 2023.1 compiler and pac_s10_usm board

2023-01-27 15:29 UTC, yuguen-intel requested changes

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +This design uses CMake to build the project. For different parts of this tutorial, navigate to the appropriate sub-folder, and create a build directory for build artifacts.
```suggestion
For different parts of this tutorial, navigate to the appropriate sub-folder.
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +cd build
```suggestion

```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +```
````suggestion
Generate the `Makefile` by running `cmake`.
  ```
  mkdir build
  cd build
  ```
  To compile for the default target (the Agilex™ device family), run `cmake` using the command:
  ```
  cmake -G "NMake Makefiles" ..
  ```
  > **Note**: You can change the default target by using the command:
  >  ```
  >  cmake -G "NMake Makefiles" .. -DFPGA_DEVICE=<FPGA device family or FPGA part number>
  >  ``` 
  >
  > Alternatively, you can target an explicit FPGA board variant and BSP by using the following command: 
  >  ```
  >  cmake -G "NMake Makefiles" .. -DFPGA_DEVICE=<board-support-package>:<board-variant>
  >  ``` 
  >
  > You will only be able to run an executable on the FPGA if you specified a BSP.
````

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  > **Note**: The Intel® PAC with Intel Arria® 10 GX FPGA and Intel® FPGA PAC D5005 (with Intel Stratix® 10 SX) do not support Windows*. Compiling to FPGA hardware on Windows* requires a third-party or
Remove this Note

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +### Run CMake on a Linux* System
```suggestion
### Run CMake to generate the Makefiles

#### On a Linux* System
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +### Run CMake on a Windows* System
```suggestion
#### On a Windows* System
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The `fpga_emu` and `fpga_sim` targets produce binaries that you can run. The executables will be called `vector_add.fpga_emu`, `vector_add.fpga_sim`, and `vector_add.fpga`. The `fpga` target will pro
```suggestion
The `fpga_emu`, `fpga_sim` and `fpga` targets produce binaries that you can run. The executables will be called `vector_add.fpga_emu`, `vector_add.fpga_sim`, and `vector_add.fpga`. 
The `fpga` target will only produce an executable binary if you create a full-system acceleration kernel.
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  ### Troubleshooting
Remove this section

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  ### In Third-Party Integrated Development Environments (IDEs)
Remove this section

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +For part 1 of this tutorial, only use the `fpga_emu` target to compile to CPU.
```suggestion
For part 1 of this tutorial, only the `fpga_emu` target is available as this regular C++ code is only capable of targeting a CPU.
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +Locate `report.html` in the `vector_add.report.prj/reports/` directory. Open the report in any of Chrome*, Firefox*, Edge*, or Internet Explorer*.
```suggestion
In part2-dcpcpp_functor_usm and part3-dcpcpp_lambda_buffers, after running the `report` target, locate `report.html` in the `vector_add.report.prj/reports/` directory. Open the report in any of Chrome*, Firefox*, Edge*, or Internet Explorer*.
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +      ```
```suggestion
    * On Linux
        ```
        CL_CONTEXT_MPSIM_DEVICE_INTELFPGA=1 ./vector_add.fpga_sim
        ```
    * On Windows
        ```
        set CL_CONTEXT_MPSIM_DEVICE_INTELFPGA=1
        vector_add.fpga_sim.exe
        set CL_CONTEXT_MPSIM_DEVICE_INTELFPGA=
        ```
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +3. Run the sample on the FPGA device (only for full-system acceleration kernel):
```suggestion
3. Run the sample on the FPGA device (only if you ran `cmake` with `-DFPGA_DEVICE=<board-support-package>:<board-variant>`):
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p1/src/CMakeLists.txt
> +set(FPGA_TARGET ${TARGET_NAME}.fpga)
```suggestion
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p1/src/CMakeLists.txt
> +add_custom_target(fpga DEPENDS ${FPGA_TARGET})
```suggestion
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p1/src/vector_add.cpp
> +void vector_add(const int *A_in, const int *B_in, int *C_out, int len) {
Function names should be CamelCase
Function arguments should be snake_case

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p1/src/vector_add.cpp
> +#define VECT_SIZE 256
```suggestion
const int vect_size 256
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p1/src/vector_add.cpp
> +    int *A = new int[count];
snake_case

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p1/src/vector_add.cpp
> +    // verify that VC is correct
VC?

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/CMakeLists.txt
> +cmake_minimum_required (VERSION 3.4)
```suggestion
cmake_minimum_required (VERSION 3.7.2)
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/CMakeLists.txt
> +# set(REPORT_TARGET ${TARGET_NAME}.report)
Why no report?

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/CMakeLists.txt
> +set(REPORT_TARGET ${TARGET_NAME}.report.a)
This is why the other one above was commented out, please move this with the other targets

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/CMakeLists.txt
> +set_target_properties(${REPORT_TARGET} PROPERTIES LINK_FLAGS "${FPGA_LINK_FLAGS} ${USER_FLAGS} -Xshardware -fsycl-link=early")
Again, all flags in the flags definitions above, for this target and the others

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +class vector_add_ID;
CamelCase

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +class vector_add {
CamelCase

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +    int *A_in;
snake_case

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +#define VECT_SIZE 256
const int

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +        // This design is tested with 2023.0, but also accounts for a syntax change in
Please only keep the 2023.1 version

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +        std::cout << "using FPGA Emulator." << std::endl;
Remove these couts

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +//         sycl::queue q(selector);
Remove commented code

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +        sycl::queue q(sycl::ext::intel::fpga_emulator_selector{});
And do not define the queue as part of the preprocessor selection:

````verbatim
#if FPGA_SIMULATOR
    auto selector = sycl::ext::intel::fpga_simulator_selector_v;
#elif FPGA_HARDWARE
    auto selector = sycl::ext::intel::fpga_selector_v;
#else  // #if FPGA_EMULATOR
    auto selector = sycl::ext::intel::fpga_emulator_selector_v;
#endif

    // create the device queue
    queue q(selector, fpga_tools::exception_handler);

    // make sure the device supports USM host allocations
    auto device = q.get_device();

    std::cout << "Running on device: "
              << device.get_info<sycl::info::device::name>().c_str()
              << std::endl;
````

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/vector_add.cpp
> +        int *A = sycl::malloc_shared<int>(count, q);
snake_case

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p3/CMakeLists.txt
> +cmake_minimum_required (VERSION 3.4)
```suggestion
cmake_minimum_required (VERSION 3.7.2)
```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p3/src/CMakeLists.txt
> +    set(FPGA_DEVICE "intel_a10gx_pac:pac_a10")
```suggestion
    set(FPGA_DEVICE "Agilex")
    message(STATUS "FPGA_DEVICE was not specified.\
                    \nConfiguring the design to the default FPGA family: ${FPGA_DEVICE}\
                    \nPlease refer to the README for information on target selection.")

```

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p3/src/CMakeLists.txt
> +# set(REPORT_TARGET ${TARGET_NAME}.report)
All the same comments as in the other cmake

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p3/src/vector_add.cpp
> +class vector_add_ID;
CamelCase

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p3/src/vector_add.cpp
> +void vector_add(const int *A_in, const int *B_in, int *C_out, int len) {
CamelCase and snake_case

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p3/src/vector_add.cpp
> +#define VECT_SIZE 256
const int

2023-01-27 15:29 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p3/src/vector_add.cpp
> +#if __INTEL_CLANG_COMPILER >= 20230100
Same remark about the selectors

2023-01-27 21:49 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +- part1-C++
they were renamed to be shorter names to avoid Windows path length limit error in regtests :(

2023-01-30 08:23 UTC, yuguen-intel commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +- part1-C++
Can you give me a path to your regtest? A recent change was merged to avoid these longpath from the regtests themselves.

2023-01-30 14:23 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +- part1-C++
I encounter the error when running locally on IOWIN a couple of weeks ago. let me change the name back and run again

2023-01-30 18:06 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +- part1-C++
You are right, It passed without a problem now.
Here is the spec link to the new run:
https://spetc.intel.com/testanalysis?trview=0&testRunIds=7500417&tapgsize=20

2023-01-31 19:29 UTC, KevinUTAT commented on DirectProgramming/DPC++FPGA/Tutorials/GettingStarted/fpga_compile/p2/src/CMakeLists.txt
> +set_target_properties(${EMULATOR_TARGET} PROPERTIES COMPILE_FLAGS "${EMULATOR_COMPILE_FLAGS} -DFPGA_EMULATOR ${USER_FLAGS}")
I think I am going to use your new cmakelist [here](https://github.com/yuguen-intel/oneAPI-samples/blob/IPA/DirectProgramming/C%2B%2BSYCL_FPGA/Tutorials/Features/ac_fixed/src/CMakeLists.txt) to be consistent

2023-02-03 08:42 UTC, yuguen-intel requested changes

2023-02-03 08:42 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part1-C++/src/vector_add.cpp
> +void vectorAdd(const int *A_in, const int *B_in, int *C_out, int len) {
Function names should be CamelCase -> VectorAdd
Variables should be snake_case -> a_in, b_in, etc.

2023-02-03 08:42 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +class vectorAddID;
Class names should be CamelCase

2023-02-03 08:42 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +    ...
This does not reflect what's in the code

2023-02-03 08:42 UTC, yuguen-intel commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +class vectorAddID;
Other files should be updated with the correct casing

2023-02-03 15:06 UTC, yuguen-intel approved these changes

2023-02-06 08:40 UTC, whitepau commented
For 'how has this been tested', please put links to your passing regtests.

2023-02-06 14:51 UTC, whitepau requested changes
we can streamline the readme by referring to docs in some places.

some small code style changes.

2023-02-06 14:51 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +| <span id="bsps">`-Xstarget=<bsp:variant>`</span>  | Instructs the compiler to target an FPGA board variant and BSP.
Can we link to the documentation instead of reproducing all the flags here? This seems a bit extra.

2023-02-06 14:51 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +There are 3 parts to this tutorial located in the 3 sub-folders. Together, they demonstrate how an algorithm can migrate from vanilla C++ code to SYCL for FPGA.
```suggestion
There are 3 parts to this tutorial located in the 3 sub-folders. Together, they demonstrate how you can migrate an algorithm from vanilla C++ code to SYCL for FPGA. Note that you may also choose to use a functor with buffers, or a function with USM.
```

2023-02-06 14:51 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The same vector addition in SYCL* C++  with a 'functor' coding style using a unified shared memory (USM) interface. Compare with the source code in part 1 to see SYCL*-specific code changes. This cod
```suggestion
The same vector addition in SYCL* C++  with a 'functor' coding style using a unified shared memory (USM) interface. Compare with the source code in part 1 to see SYCL*-specific code changes. Observe how the `VectorAdd` functor is called using `q.single_task<...>(VectorAdd{...});`. This tells the DPC++ compiler to convert `VectorAdd` into RTL. Also observe how `vec_a`, `vec_b`, and `vec_c` are allocated into a shared memory space using `malloc_shared`; this tells the DPC++ compiler that `vec_a`, `vec_b`, and `vec_c` should be visible both to your kernel and your host code (or if you are creating an IP component, the testbench code).
```

This coding style does not really improve the clarity of device/host code separation.

2023-02-06 14:51 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +        //  - the simulator device
```suggestion
        // Select either:
        //  - the FPGA emulator device (CPU emulation of the FPGA)
        //  - the FPGA device (a real FPGA)
        //  - the simulator device 
```
```suggestion
        // Use compile-time macros to select either:
        //  - the FPGA emulator device (CPU emulation of the FPGA)
        //  - the FPGA device (a real FPGA)
        //  - the simulator device 
```

2023-02-06 14:51 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +        auto device = q.get_device();
does this actually ensure that USM host allocations are supported?

2023-02-06 14:51 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +        // verify that VC is correct
```suggestion
        // verify that vec_c is correct
```

2023-02-06 14:51 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part1-C++/src/vector_add.cpp
> +const int vect_size = 256;
```suggestion
constexpr int kVectSize = 256;
```

2023-02-06 15:42 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +In the FPGA IP component authoring flow, you can generate a reusable IP component that you can import into an Intel® Quartus® Prime project. You can generate an IP by targeting your compilation to a
Interesting. I am getting 
```
Error: 'AGFB014R24A3EV' does not specify a valid device, device family, or board variant.
Please make sure the option -Xstarget points to a valid board variant
```

2023-02-06 18:46 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +In *part2-dcpcpp_functor_usm* and *part3-dcpcpp_lambda_buffers*, after running the `report` target, locate `report.html` in the `vector_add.report.prj/reports/` directory. Open the report in any of C
I will change to using `fpga_report`

2023-02-06 19:04 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part2-dpcpp_functor_usm/src/vector_add.cpp
> +        auto device = q.get_device();
it is ambiguous to mention it here as a comment, should remove it, this is already mentioned in the readme

2023-02-06 20:55 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +In the FPGA IP component authoring flow, you can generate a reusable IP component that you can import into an Intel® Quartus® Prime project. You can generate an IP by targeting your compilation to a
i am changing the example to `AGFA014R24B1E1V`, this number seems to work with 2023.1 rel/

2023-02-07 20:09 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The FPGA IP component authoring flow does not generate any FPGA accelerated executable, only RTL (Register Transfer Level) IP component files. The host application is  treated only as a 'testbench' t
Full-system design => Multiarchitecture Binary
IP Authoring => IP component generation

2023-02-09 17:46 UTC, KevinUTAT commented
Add two more parts to the sample: functor buffers and lambda USM. The SPEC link will be updated once they are finished

2023-02-09 19:50 UTC, whitepau reviewed
after these minor changes, I approve of it being sent to the main repo.

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part3-dpcpp_lambda_buffers/src/vector_add.cpp
> +constexpr int kVectSize  = 256;
i have no comment on this one. :)

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part5-dpcpp_lambda_usm/src/vector_add.cpp
> +        int *vec_c = malloc_shared<int>(kVectSize, q);
good choice to use host allocations because IP Authoring simulation doesn't support device allocations

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part5-dpcpp_lambda_usm/src/vector_add.cpp
> +        for (int i = 0; i < kVectSize; i++) {
```suggestion
        // verify that vec_c is correct
        for (int i = 0; i < kVectSize; i++) {
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part5-dpcpp_lambda_usm/src/vector_add.cpp
> +        for (int i = 0; i < kVectSize; i++) {
spacing should align with other code samples so that users can easily diff between them

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +### Multiarchitecture binary vs reusable IP components
```suggestion
### Multiarchitecture binary vs IP component
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +In the FPGA multiarchitecture binary generation flow, you can generate an executable host application and acceleration kernel for a PCIe FPGA board if you have a compatible board support package (BSP
```suggestion
In the FPGA multiarchitecture binary generation flow, you can generate an executable host application and accelerator for a PCIe FPGA board if you have a compatible board support package (BSP). Intel provides BSPs for the Intel® PAC with Intel Arria® 10 GX FPGA, and the Intel® FPGA PAC D5005 (with Intel Stratix® 10 SX). If you have a different board, check with your vendor to see if they supply a BSP.
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +In the FPGA IP component generation flow, you can generate a reusable IP component that you can import into an Intel® Quartus® Prime project. You can generate an IP by targeting your compilation to a
```suggestion
In the FPGA IP component generation flow, you can generate an IP component that you can import into an Intel® Quartus® Prime project. You can generate an IP by targeting your compilation to a supported Intel® FPGA device family or part number (for example, `Agilex` or `AGFA014R24B1E1V`) instead of a named board (for example, `intel_a10gx_pac:pac_a10`). 
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The FPGA IP component generation flow does not generate any FPGA accelerated executable, only RTL (Register Transfer Level) IP component files. The host application is  treated only as a 'testbench'
```suggestion
The FPGA IP component generation flow does not generate any FPGA accelerated executable, only RTL (Register Transfer Level) IP component files. The host application is treated only as a 'testbench' that exercises and validates your IP component in emulation and simulation.
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The FPGA emulator is the fastest method to verify the correctness of your code. The FPGA emulator executes the SYCL* device code on the CPU. The emulator is similar to the SYCL* host device, but unli
```suggestion
The FPGA emulator is the fastest method to verify the correctness of your code. The FPGA emulator executes the SYCL* device code on the CPU. The emulator is similar to the SYCL* host device, but unlike the host device, the FPGA emulator device supports FPGA extensions such as FPGA pipes and `fpga_reg` (although some of these features, such as `fpga_reg` may not affect how your design runs on the emulator).
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The [FPGA Optimization Guide for Intel® oneAPI Toolkits Developer Guide][1] contains a chapter about how to analyze the reports generated after the FPGA early image and FPGA image.
fancy markdown syntax 👍👍👍

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +If the compilation flow is for the multiarchitecture binary, the result is an FPGA hardware binary (also referred to as a bitstream) that is executable if you target a supported BSP. The compiler wil
```suggestion
If you compile a multiarchitecture binary, the resulting binary will include an FPGA hardware image (also referred to as a bitstream) that is executable on an FPGA accelerator card with a supported BSP. The compiler will interface your design with the BSP, and your host application will seamlessly make the system calls to launch kernels on the FPGA. 
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
>  If the compilation flow is for reusable IP component, the compilation result is **not** executable. IP components are compiled in isolation and not interfaced with other components on the FPGA. The p
```suggestion
If you compile an IP component, the compilation result is **not** executable. IP components are compiled in isolation and not interfaced with other components on the FPGA. The purpose of this compilation flow is to get accurate resource utilization and performance data for IP components.
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +It is recommended to use a preprocessor define to choose between the emulator and FPGA selectors. This makes it easy to switch between targets using only command-line options. Since the FPGA only sup
```suggestion
It is recommended to use a preprocessor macro to choose between the emulator and FPGA selectors. This makes it easy to switch between targets using only command-line options. Since the FPGA only supports ahead-of-time compilation, dynamic selectors (such as the `default_selector`) are less useful than explicit selectors when targeting FPGA.
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +>**Note:** In this sample, the compiler is refered to as `icpx`. On Windows, you should use `icx-cl`.
```suggestion
> **Note**: In this sample, the compiler is refered to as `icpx`. On Windows, you should use `icx-cl`.
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The same vector addition in SYCL* C++  with a 'functor' coding style using unified shared memory (USM) interface. Compare with the source code in part 1 to see SYCL*-specific code changes. Observe ho
```suggestion
Part 2 shows the same vector addition from part 1, but in SYCL* C++  with a 'functor' coding style using a unified shared memory (USM) interface. Compare with the source code in part 1 to see SYCL*-specific code changes. Observe how the `VectorAdd` functor is called using `q.single_task<...>(VectorAdd{...});`. This tells the DPC++ compiler to convert `VectorAdd` into RTL. Also observe how `vec_a`, `vec_b`, and `vec_c` are allocated into a shared memory space using `malloc_shared`; this tells the DPC++ compiler that `vec_a`, `vec_b`, and `vec_c` should be visible both to your kernel and your host code (or if you are creating an IP component, the testbench code).
```

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The same vector addition in SYCL* C++ with a 'function' coding style using unified shared memory (USM)
```suggestion
#### Part 5 SYCL* (lambda function and USM)
Part 5 demonstrates vector addition in SYCL* C++ with a 'function' coding style using unified shared memory (USM). This code style will be familiar to users who are already experienced with SYCL*. Observe how the `VectorAdd` function is called using a lambda expression:
```c++
h.single_task<...>([=]() {
    VectorAdd(...);
});
```
```

I think this should be part 3. that way we only change one thing between part 2 and 3 (namely, we switch from a functor to a function).

Use the lambda explanation that we already have.

eventually, when mm host attributes can be applied to pointer arguments, we can stop advocating the functor model :)

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +This tells the DPC++ compiler to convert `VectorAdd` into RTL. Also observe how `vec_a`, `vec_b`, and `vec_c` are copied into buffers before the `VectorAdd` function is called.
```suggestion
#### Part 3 SYCL* (lambda function and buffer)
Part 3 shows the vector addition in SYCL* C++ with a 'function' coding style and buffer & accessor interface. This code style will be familiar to users who are already experienced with SYCL*. Observe how `vec_a`, `vec_b`, and `vec_c` are copied into buffers before the `VectorAdd` function is called.
```

this should be part 4

2023-02-09 19:50 UTC, whitepau commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/README.md
> +The same vector addition in SYCL* C++  with a 'functor' coding style using buffer & accessor interface
```suggestion
Part 4 demonstrates the vector addition in SYCL* C++  with a 'functor' coding style using buffer & accessor interface. Observe how template parameters are used in the functor to pass in the accessors.
```
this should be part 5

2023-02-09 20:04 UTC, KevinUTAT commented on DirectProgramming/C++SYCL_FPGA/Tutorials/GettingStarted/fpga_compile/part1-C++/src/CMakeLists.txt
> +add_custom_target(fpga DEPENDS ${FPGA_TARGET})
Would the output mismatch with reg.rout doing this? if I don't run part1 for sim and default, the output would be missing a "PASSED" compared to emulation

2023-02-10 09:13 UTC, whitepau approved these changes

2023-02-10 15:48 UTC, KevinUTAT commented
Closing this PR in preparation of make a new one to the main repo

2023-02-10 15:48 UTC, closed without merging